### ISSUE TITLE
Not working on IOS this happens from version 1.2.9 and up

### ISSUE THREAD

**Issue by AchrafBardan** [nativescript-community/ui-label#13]
### Which platform(s) does your issue occur on?
- iOS
- iOS 15.4
- emulator

This has something to do with the maxLinesPropery.
```
NativeScript encountered a fatal error: Uncaught TypeError: Cannot read property 'setNative' of undefined
  at
  ./node_modules/@nativescript-community/ui-label/label.ios.js(file: app/webpack:/rapi-freelancer-app/node_modules/@nativescript-community/ui-label/label.ios.js:621:5)
  at __webpack_require__(file: app/webpack:/rapi-freelancer-app/webpack/bootstrap:24:0)
  at fn(file: app/webpack:/rapi-freelancer-app/webpack/runtime/hot module replacement:61:0)
  at ./app/vendor/components.ts(file: app/webpack:/rapi-freelancer-app/app/vendor/components.ts:4:0)
  at __webpack_require__(file: app/webpack:/rapi-freelancer-app/webpack/bootstrap:24:0)
  at fn(file: app/webpack:/rapi-freelancer-app/webpack/runtime/hot module replacement:61:0)
  at ./app/app.ts(file:///app/bundle.js:19:76)
  at __webpack_require__(file: app/webpack:/rapi-freelancer-app/webpack/bootstrap:24:0)
  at __webpack_exec__(file:///app/bundle.js:12881:39)
  at (file:///app/bundle.js:12882:221)
  at __webpack_require__.X(file: app/webpack:/rapi-freelancer-app/webpack/runtime/startup entrypoint:6:0)
  at (file:///app/bundle.js:12882:47)
  at (file:///app/bundle.js:12887:3)
  at require(:1:137)
```

**Comment by farfromrefug** [comment]
@AchrafBardan There was a breaking change in N. Consequently this plugin latest versions requires  latest N versions.
Sorry about that
